/**
 * GENERATED by `web/tools/gen-champion-catalogue.mjs` from
 * `client/scripts/CHAMPIONCAGE.as` and the live English string table. Do not
 * edit by hand: change the generator and run `npm run gen:champion-catalogue`
 * from `web/`.
 *
 * Written twice, byte for byte identical: `web/src/game/yard/championCatalogue.ts`
 * and `server/src/game-data/championCatalogue.ts`. It imports nothing so the
 * same text compiles in either package.
 *
 * The champions (`docs/specs/monsters-and-hatchery.md` §7): per-level stats,
 * the feeding economy and the Map Room 2 feed recipes. Levels run 1 to
 * `levels` (6 for the four basic champions, 5 for Krallen); every per-level
 * ladder is read through {@link atChampionLevel}, which clamps like the
 * original `CHAMPIONCAGE.GetGuardianProperty` (`CHAMPIONCAGE.as:401-416`).
 */

/** Monsters one feed consumes: `{ monsterId: count }`. */
export type FeedRecipe = Readonly<Record<string, number>>;

export interface ChampionEntry {
  /** `G1`..`G5`. */
  readonly id: string;
  /** The `t` a save's `champion` entry carries. */
  readonly t: number;
  readonly name: string;
  /** The second line of the original title card, e.g. "High Defense"; null for Krallen. */
  readonly role: string | null;
  readonly description: string;
  /** `basic` champions live in the cage one at a time; Krallen is `special`. */
  readonly kind: "basic" | "special";
  /** True for a champion the cage offers to raise (`CanTrainGuardian`, `CHAMPIONCAGE.as:459-461`). */
  readonly raisable: boolean;
  readonly powerLevel: number;
  /** The highest evolution level. */
  readonly levels: number;
  /** Seconds a feed lasts before the champion is hungry. */
  readonly feedTime: number;
  readonly bonusFeedTime: number;
  readonly health: readonly number[];
  readonly damage: readonly number[];
  readonly speed: readonly number[];
  readonly range: readonly number[];
  /** Seconds from empty to full health in the cage, by level. */
  readonly healtime: readonly number[];
  readonly buffs: readonly number[];
  /** Feeds that evolve the champion out of each level (1..5). */
  readonly feedCount: readonly number[];
  /** Shiny for one feed at each level (1..5). */
  readonly feedShiny: readonly number[];
  /** Shiny for a level-6 food-bonus feed, by the rank it raises to (1..3). */
  readonly bonusFeedShiny: readonly number[];
  /** Food-bonus ranks 1..3 add these to the top level's stats. */
  readonly bonusHealth: readonly number[];
  readonly bonusDamage: readonly number[];
  readonly bonusSpeed: readonly number[];
  readonly bonusRange: readonly number[];
  readonly bonusBuffs: readonly number[];
  /** Map Room 2 feed recipe at each level (1..5). */
  readonly feeds: readonly FeedRecipe[];
  /** Map Room 2 food-bonus recipe, by the rank it raises to (1..3). */
  readonly bonusFeeds: readonly FeedRecipe[];
}

/** Seconds of grace after a champion turns hungry before it starves (`CHAMPIONCAGE.STARVETIMER`). */
export const STARVE_SECONDS = 86400;

/** The highest food-bonus rank (`CHAMPIONCAGE.as:697-786`). */
export const MAX_FOOD_BONUS = 3;

export const CHAMPION_CATALOGUE: readonly ChampionEntry[] = [
  {
    // `client/scripts/CHAMPIONCAGE.as:46`; feeds at `:539`.
    id: "G1",
    t: 1,
    name: "Gorgo",
    role: "High Defense",
    description: "Discovered inside the Bermuda Triangle, Gorgo is a powerful 'tank' monster of simian origin.",
    kind: "basic",
    raisable: true,
    powerLevel: 1,
    levels: 6,
    feedTime: 82800,
    bonusFeedTime: 86400,
    health: [40000, 80000, 120000, 140000, 160000, 200000],
    damage: [1000, 1200, 1500, 2000, 2500, 3000],
    speed: [1, 1.2, 1.4, 1.6, 1.8, 2],
    range: [35, 45, 55, 65, 70, 70],
    healtime: [3600, 7200, 14400, 28800, 57600, 115200],
    buffs: [0],
    feedCount: [3, 6, 9, 12, 15],
    feedShiny: [26, 44, 75, 111, 136],
    bonusFeedShiny: [136, 136, 136],
    bonusHealth: [12500, 27500, 50000],
    bonusDamage: [150, 330, 600],
    bonusSpeed: [0.1, 0.2, 0.4],
    bonusRange: [0, 0, 0],
    bonusBuffs: [0, 0, 0],
    feeds: [{ C2: 15 }, { C2: 10, C6: 5 }, { C6: 20 }, { C6: 10, C10: 10 }, { C10: 20 }],
    bonusFeeds: [{ C10: 20 }, { C10: 20 }, { C10: 20 }],
  },
  {
    // `client/scripts/CHAMPIONCAGE.as:89`; feeds at `:547`.
    id: "G2",
    t: 2,
    name: "Drull",
    role: "High Attack",
    description: "Covered in red obsidian scales, this two-headed beast delivers overwhelming damage during attacks.",
    kind: "basic",
    raisable: true,
    powerLevel: 1,
    levels: 6,
    feedTime: 82800,
    bonusFeedTime: 86400,
    health: [12000, 20000, 36000, 42000, 52000, 60000],
    damage: [3000, 3600, 4200, 5500, 6500, 8000],
    speed: [2, 2.2, 2.5, 2.8, 3.2, 3.6],
    range: [35, 45, 55, 65, 85, 90],
    healtime: [3600, 7200, 14400, 28800, 57600, 115200],
    buffs: [0],
    feedCount: [3, 6, 9, 12, 15],
    feedShiny: [26, 44, 75, 105, 131],
    bonusFeedShiny: [131, 131, 131],
    bonusHealth: [2500, 5500, 10000],
    bonusDamage: [400, 880, 1600],
    bonusSpeed: [0.1, 0.2, 0.4],
    bonusRange: [0, 0, 0],
    bonusBuffs: [0, 0, 0],
    feeds: [{ C1: 30 }, { C1: 20, C4: 15 }, { C7: 50 }, { C7: 10, C8: 15 }, { C8: 30 }],
    bonusFeeds: [{ C8: 30 }, { C8: 30 }, { C8: 30 }],
  },
  {
    // `client/scripts/CHAMPIONCAGE.as:132`; feeds at `:555`.
    id: "G3",
    t: 3,
    name: "Fomor",
    role: "Buffs Monsters",
    description: "Known in the northern isles as the 'Flying Frog of Death', Fomor's presence provides a 'buff' to your monster army, granting armor and speed to nearby monsters.",
    kind: "basic",
    raisable: true,
    powerLevel: 1,
    levels: 6,
    feedTime: 82800,
    bonusFeedTime: 86400,
    health: [15000, 17500, 20000, 22500, 25000, 40000],
    damage: [70, 80, 90, 100, 110, 120],
    speed: [1.2, 1.4, 2, 2.1, 2.2, 2.3],
    range: [140, 140, 180, 190, 200, 210],
    healtime: [3600, 7200, 14400, 28800, 57600, 115200],
    buffs: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6],
    feedCount: [3, 6, 9, 12, 15],
    feedShiny: [26, 45, 62, 76, 96],
    bonusFeedShiny: [96, 96, 96],
    bonusHealth: [1000, 2200, 4000],
    bonusDamage: [3, 6, 10],
    bonusSpeed: [0.1, 0.2, 0.4],
    bonusRange: [3, 6, 10],
    bonusBuffs: [0.03, 0.06, 0.15],
    feeds: [{ C3: 20 }, { C3: 20, C9: 2 }, { C3: 40, C9: 5 }, { C3: 30, C9: 10 }, { C9: 20 }],
    bonusFeeds: [{ C9: 20 }, { C9: 20 }, { C9: 20 }],
  },
  {
    // `client/scripts/CHAMPIONCAGE.as:178`; feeds at `:566`.
    id: "G4",
    t: 4,
    name: "Korath",
    role: "Inferno Monster",
    description: "Spawned in the magma pits of Inferno, Korath uses his massive body and fiery core to eliminate enemies.",
    kind: "basic",
    raisable: false,
    powerLevel: 0,
    levels: 6,
    feedTime: 82800,
    bonusFeedTime: 86400,
    health: [28000, 62000, 96000, 120000, 144000, 175000],
    damage: [2000, 2400, 3000, 3800, 5000, 6500],
    speed: [1.4, 1.6, 1.8, 2, 2.3, 2.5],
    range: [35, 45, 55, 60, 65, 65],
    healtime: [3600, 7200, 14400, 28800, 57600, 115200],
    buffs: [0],
    feedCount: [3, 6, 9, 12, 15],
    feedShiny: [26, 44, 75, 111, 136],
    bonusFeedShiny: [96, 96, 96],
    bonusHealth: [1000, 2200, 4000],
    bonusDamage: [300, 600, 1000],
    bonusSpeed: [0.1, 0.2, 0.4],
    bonusRange: [0, 0, 0],
    bonusBuffs: [0],
    feeds: [{ IC1: 20, IC2: 10 }, { IC2: 10, IC7: 2 }, { IC7: 6 }, { IC7: 10 }, { IC8: 3 }],
    bonusFeeds: [{ IC8: 3 }, { IC8: 3 }, { IC8: 3 }],
  },
  {
    // `client/scripts/CHAMPIONCAGE.as:223`; feeds at `:223`.
    id: "G5",
    t: 5,
    name: "Krallen",
    role: null,
    description: "Born in the blood-soaked grasslands of southeast Asia, Krallen can survive in any climate - wet or dry. He thinks only of his next kill.",
    kind: "special",
    raisable: false,
    powerLevel: 0,
    levels: 5,
    feedTime: 82800,
    bonusFeedTime: 86400,
    health: [50000, 52000, 54000, 58000, 62000],
    damage: [800, 850, 900, 1000, 1200],
    speed: [2.2, 2.3, 2.4, 2.5, 2.6],
    range: [35, 45, 55, 60, 65],
    healtime: [7200, 14400, 28800, 57600, 115200],
    buffs: [0.2, 0.22, 0.24, 0.27, 0.3],
    feedCount: [3, 6, 9, 12, 15],
    feedShiny: [26, 44, 75, 111, 136],
    bonusFeedShiny: [96, 96, 96],
    bonusHealth: [0, 0, 0],
    bonusDamage: [0, 0, 0],
    bonusSpeed: [0, 0, 0],
    bonusRange: [0, 0, 0],
    bonusBuffs: [0],
    feeds: [{ IC1: 20, IC2: 10 }, { IC2: 10, IC7: 2 }, { IC7: 6 }, { IC7: 10 }, { IC8: 3 }],
    bonusFeeds: [{ IC8: 3 }, { IC8: 3 }, { IC8: 3 }],
  },
];

/** The champion with type `t` (1..5) or id `G1`..`G5`; undefined for anything else. */
export const championEntry = (key: number | string): ChampionEntry | undefined =>
  CHAMPION_CATALOGUE.find((entry) => entry.t === key || entry.id === key);

/**
 * `ladder` at `level`, clamped to its last entry and to at least level 1, as
 * `CHAMPIONCAGE.GetGuardianProperty` reads every per-level prop.
 */
export const atChampionLevel = (ladder: readonly number[], level: number): number => {
  const clamped = Math.min(Math.max(Math.trunc(level) || 1, 1), ladder.length);
  return ladder[clamped - 1] ?? 0;
};

/** The recipe `ladder` holds at `step`, clamped the same way. */
const recipeAt = (ladder: readonly FeedRecipe[], step: number): FeedRecipe => {
  const clamped = Math.min(Math.max(Math.trunc(step) || 1, 1), ladder.length);
  return ladder[clamped - 1] ?? {};
};

/**
 * Full health at `level` with `foodBonus` ranks: the level's health plus the
 * rank's bonus (`client/scripts/com/monsters/monsters/champions/ChampionBase.as:127-132`).
 */
export const championMaxHealth = (entry: ChampionEntry, level: number, foodBonus: number): number =>
  atChampionLevel(entry.health, level) +
  (foodBonus > 0 ? atChampionLevel(entry.bonusHealth, foodBonus) : 0);

/**
 * What one feed with monsters eats: the level's recipe below the top level,
 * the next food-bonus rank's at the top (`FeedGuardian`, `CHAMPIONCAGE.as:691-697`;
 * a champion already at rank 3 eats rank 3's).
 */
export const feedRecipe = (entry: ChampionEntry, level: number, foodBonus: number): FeedRecipe =>
  level >= entry.levels
    ? recipeAt(entry.bonusFeeds, foodBonus + 1)
    : recipeAt(entry.feeds, level);

/**
 * Shiny for one feed. Below the top level the level's `feedShiny`; at the top
 * the next rank's `bonusFeedShiny`, doubled when the champion is not hungry
 * (`CHAMPIONCAGE.as:702-709`, `CHAMPIONCAGEPOPUP.as:1240-1246`).
 */
export const feedShinyPrice = (
  entry: ChampionEntry,
  level: number,
  foodBonus: number,
  hungry: boolean,
): number =>
  level >= entry.levels
    ? atChampionLevel(entry.bonusFeedShiny, foodBonus + 1) * (hungry ? 1 : 2)
    : atChampionLevel(entry.feedShiny, level);

/**
 * Shiny to evolve now: `feedShiny × 2 × feeds still needed`
 * (`CHAMPIONCAGEPOPUP.as:1208-1238`; the `evolveShiny` table is never read).
 */
export const evolveShinyPrice = (entry: ChampionEntry, level: number, feeds: number): number =>
  atChampionLevel(entry.feedShiny, level) *
  2 *
  Math.max(0, atChampionLevel(entry.feedCount, level) - Math.max(0, Math.trunc(feeds) || 0));
