import type { MapRoom1Response } from "@/api/maproom1";

/**
 * A Map Room 1 answer shaped like the approved mock-ups (issue #132): four
 * tribes, one of them wrecked, and neighbours in every state the card has
 * words for. The tests read it, and so does the DEV-only `?mr1fixture` mount
 * that shows every card state without touching the server. In the route's
 * own shape (`docs/server-api.md` "Map Room 1 read"). Times are relative to
 * `now` so the countdowns are live.
 */
export const mapRoom1Fixture = (now: number): MapRoom1Response => ({
  error: 0,
  now,
  level: 6,
  protectedUntil: now + 2 * 86_400 + 4 * 3_600,
  tribes: [
    {
      baseid: "1",
      tribe: "Legionnaire",
      tier: "TH3",
      level: 5,
      destroyed: 0,
      damage: 0,
      respawnAt: 0,
    },
    {
      baseid: "11",
      tribe: "Kozu",
      tier: "TH3",
      level: 6,
      destroyed: 0,
      damage: 40,
      respawnAt: 0,
    },
    {
      baseid: "21",
      tribe: "Abunakki",
      tier: "TH3",
      level: 7,
      destroyed: 1,
      damage: 95,
      respawnAt: now + 432,
    },
    {
      baseid: "31",
      tribe: "Dreadnaut",
      tier: "TH3",
      level: 8,
      destroyed: 0,
      damage: 0,
      respawnAt: 0,
    },
  ],
  neighbours: [
    {
      userid: 901,
      baseid: "90101",
      baseseed: 7,
      username: "Mossbeard",
      level: 9,
      attacksfrom: 2,
      attacksto: 1,
      saved: now - 3 * 3_600,
      attackpermitted: 1,
    },
    {
      userid: 902,
      baseid: "90202",
      baseseed: 3,
      username: "Bramblefoot",
      level: 8,
      saved: now - 20,
      attackpermitted: 1,
    },
    {
      userid: 903,
      baseid: "90303",
      baseseed: 11,
      username: "Grimble",
      level: 7,
      saved: now - 86_400,
      attackpermitted: 1,
    },
    {
      userid: 904,
      baseid: "90404",
      baseseed: 5,
      username: "Nettlejaw",
      level: 3,
      saved: now - 7_200,
      attackpermitted: 6,
      protectedUntil: now + 5 * 86_400,
    },
    {
      userid: 905,
      baseid: "90505",
      baseseed: 13,
      username: "Toadstool",
      level: 5,
      saved: now - 40_000,
      attackpermitted: 5,
      protectedUntil: now + 31 * 3_600,
    },
    {
      userid: 906,
      baseid: "90606",
      baseseed: 2,
      username: "Pip Squeak",
      level: 4,
      saved: now - 600_000,
      attackpermitted: 1,
    },
    {
      userid: 907,
      baseid: "90707",
      baseseed: 9,
      username: "Wartwhistle",
      level: 6,
      attacksto: 3,
      saved: now - 9_000,
      attackpermitted: 7,
      attacker: "Grimble",
    },
    {
      userid: 908,
      baseid: "90808",
      baseseed: 4,
      username: "Fernwick",
      level: 6,
      saved: now - 50_000,
      attackpermitted: 9,
      trucestate: "accepted",
      truceexpire: 9 * 86_400,
    },
    {
      userid: 909,
      baseid: "90909",
      baseseed: 12,
      username: "Sludgepot",
      level: 5,
      attacksfrom: 1,
      saved: now - 200_000,
      attackpermitted: 1,
    },
  ],
});
