/**
 * Monster sprite sheets, one entry per sheet. GENERATED — do not edit by hand.
 *
 * Source: `client/scripts/SPRITES.as`, the `SpriteData` lines in `Setup()`
 * (`:17-96`) and the drawing rules in `GetSprite()` (`:119-375`), with the
 * champion anchors from `client/scripts/CHAMPIONCAGE.as` and each creep's
 * movement from `client/scripts/CREATURELOCKER.as`. Regenerate with
 * `npm run gen:monster-sprites` from `web/`.
 *
 * A sheet is a grid of `frameWidth` x `frameHeight` cells. Columns are
 * headings and rows are animation frames (`SPRITES.as:377-381`): cell
 * `(column, row)` is the rectangle at `(column * frameWidth, row * frameHeight)`.
 * `columns` and `rows` are what the PNG on disk really holds; `directions`
 * is how many headings `GetSprite` splits the circle into, which for a few
 * sheets is not the same number. `anchorX`/`anchorY` is the pixel of the cell
 * that sits on the monster's ground point. The helpers in `monsterSprites.ts`
 * turn a heading and a tick into a cell.
 */

/** The animation states the table distinguishes. Absent ones fall back; see `frameRow`. */
export type MonsterAnimation =
  | "idle"
  | "walk"
  | "attack"
  | "stomp"
  | "invisible"
  | "landed"
  | "carrying"
  | "hardhat"
  | "burrowed"
  | "transition";

/** A run of rows: `first + floor(tick / ticksPerFrame) % count`. */
export interface RowCycle {
  readonly first: number;
  readonly count: number;
  readonly ticksPerFrame: number;
}

export interface MonsterSheet {
  /** The `SPRITES.as` key: `C1`, `IC3`, `G1_4`, `shadow`. */
  readonly key: string;
  /** `G1` for `G1_4`; the key itself otherwise. */
  readonly family: string;
  /** Path under the game server's `/assets/`. */
  readonly file: string;
  readonly width: number;
  readonly height: number;
  /** Fractional for one sheet (Zagnoid, 64.4). */
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly columns: number;
  readonly rows: number;
  readonly anchorX: number;
  readonly anchorY: number;
  /** Headings around the circle: 30, 32, 16, or 1 for a shadow. */
  readonly directions: number;
  /** Degrees subtracted from the heading before it is split into columns; 45 for champions. */
  readonly directionOffset: number;
  readonly animations: Readonly<Partial<Record<MonsterAnimation, RowCycle>>>;
  /** `ground`, `fly`, `burrow` or `jump` as the creature table has it. */
  readonly movement: string;
  /** The shadow sheet a flyer draws under itself, or null. */
  readonly shadow: "shadow" | "bigshadow" | null;
  /** Sheet keys a skin may swap in for this one. */
  readonly skins: readonly string[];
}

export const MONSTER_SPRITES: Readonly<Record<string, MonsterSheet>> = {
  // SPRITES.as:20, rules :130
  worker: {
    key: "worker",
    family: "worker",
    file: "monsters/worker.png",
    width: 810,
    height: 54,
    frameWidth: 27,
    frameHeight: 27,
    columns: 30,
    rows: 2,
    anchorX: 9,
    anchorY: 19,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
      hardhat: { first: 1, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:23, rules :130
  infernoWorker: {
    key: "infernoWorker",
    family: "infernoWorker",
    file: "monsters/inferno_worker.v2.png",
    width: 1920,
    height: 55,
    frameWidth: 64,
    frameHeight: 55,
    columns: 30,
    rows: 1,
    anchorX: 32,
    anchorY: 36,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:25, rules :369
  C1: {
    key: "C1",
    family: "C1",
    file: "monsters/sprite.1.v1.png",
    width: 720,
    height: 21,
    frameWidth: 24,
    frameHeight: 21,
    columns: 30,
    rows: 1,
    anchorX: 8,
    anchorY: 14,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:26, rules :369
  C2: {
    key: "C2",
    family: "C2",
    file: "monsters/octoooze.png",
    width: 1170,
    height: 28,
    frameWidth: 39,
    frameHeight: 28,
    columns: 30,
    rows: 1,
    anchorX: 19,
    anchorY: 15,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:27, rules :369
  C3: {
    key: "C3",
    family: "C3",
    file: "monsters/sprite.3.v2.png",
    width: 900,
    height: 28,
    frameWidth: 30,
    frameHeight: 28,
    columns: 30,
    rows: 1,
    anchorX: 7,
    anchorY: 20,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:28, rules :369
  C4: {
    key: "C4",
    family: "C4",
    file: "monsters/fink.png",
    width: 1020,
    height: 32,
    frameWidth: 34,
    frameHeight: 32,
    columns: 30,
    rows: 1,
    anchorX: 15,
    anchorY: 21,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:29, rules :369
  C5: {
    key: "C5",
    family: "C5",
    file: "monsters/eyera.png",
    width: 780,
    height: 23,
    frameWidth: 26,
    frameHeight: 23,
    columns: 30,
    rows: 1,
    anchorX: 11,
    anchorY: 15,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:30, rules :369
  C6: {
    key: "C6",
    family: "C6",
    file: "monsters/ichi.png",
    width: 810,
    height: 26,
    frameWidth: 27,
    frameHeight: 26,
    columns: 30,
    rows: 1,
    anchorX: 11,
    anchorY: 17,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:31, rules :369
  C7: {
    key: "C7",
    family: "C7",
    file: "monsters/bandito.png",
    width: 870,
    height: 28,
    frameWidth: 29,
    frameHeight: 28,
    columns: 30,
    rows: 1,
    anchorX: 11,
    anchorY: 17,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:32, rules :369
  C8: {
    key: "C8",
    family: "C8",
    file: "monsters/fang.png",
    width: 1020,
    height: 31,
    frameWidth: 34,
    frameHeight: 31,
    columns: 30,
    rows: 1,
    anchorX: 16,
    anchorY: 19,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:33, rules :142
  C9: {
    key: "C9",
    family: "C9",
    file: "monsters/brain.v2.png",
    width: 1020,
    height: 48,
    frameWidth: 34,
    frameHeight: 24,
    columns: 30,
    rows: 2,
    anchorX: 16,
    anchorY: 13,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
      invisible: { first: 1, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:34, rules :369
  C10: {
    key: "C10",
    family: "C10",
    file: "monsters/crabatron.png",
    width: 1110,
    height: 27,
    frameWidth: 37,
    frameHeight: 27,
    columns: 30,
    rows: 1,
    anchorX: 15,
    anchorY: 18,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:35, rules :369
  C11: {
    key: "C11",
    family: "C11",
    file: "monsters/sprite.11.v2.png",
    width: 1440,
    height: 34,
    frameWidth: 48,
    frameHeight: 35,
    columns: 30,
    rows: 1,
    anchorX: 24,
    anchorY: 22,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:36, rules :154
  C12: {
    key: "C12",
    family: "C12",
    file: "monsters/sprite.12.v2.png",
    width: 1590,
    height: 46,
    frameWidth: 53,
    frameHeight: 46,
    columns: 30,
    rows: 1,
    anchorX: 21,
    anchorY: 27,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: ["C12Gold"],
  },
  // SPRITES.as:37, rules :369
  C12Gold: {
    key: "C12Gold",
    family: "C12Gold",
    file: "monsters/sprite.12.gold.png",
    width: 1590,
    height: 46,
    frameWidth: 53,
    frameHeight: 46,
    columns: 30,
    rows: 1,
    anchorX: 21,
    anchorY: 27,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:38, rules :160
  C13: {
    key: "C13",
    family: "C13",
    file: "monsters/13.png",
    width: 1280,
    height: 27,
    frameWidth: 40,
    frameHeight: 26,
    columns: 32,
    rows: 1,
    anchorX: 19,
    anchorY: 17,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "burrow",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:39, rules :180
  C14: {
    key: "C14",
    family: "C14",
    file: "monsters/14.v1.png",
    width: 896,
    height: 84,
    frameWidth: 28,
    frameHeight: 28,
    columns: 32,
    rows: 3,
    anchorX: 15,
    anchorY: 14,
    directions: 32,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 3, ticksPerFrame: 3 },
      landed: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "shadow",
    skins: [],
  },
  // SPRITES.as:40, rules :205
  C15: {
    key: "C15",
    family: "C15",
    file: "monsters/zafreeti.v2.png",
    width: 1792,
    height: 70,
    frameWidth: 56,
    frameHeight: 70,
    columns: 32,
    rows: 1,
    anchorX: 28,
    anchorY: 35,
    directions: 32,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "bigshadow",
    skins: [],
  },
  // SPRITES.as:41, rules :186
  C16: {
    key: "C16",
    family: "C16",
    file: "monsters/vorg_anim.png",
    width: 1280,
    height: 120,
    frameWidth: 40,
    frameHeight: 40,
    columns: 32,
    rows: 3,
    anchorX: 26,
    anchorY: 36,
    directions: 32,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 3, ticksPerFrame: 3 },
      landed: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "shadow",
    skins: [],
  },
  // SPRITES.as:42, rules :369
  C17: {
    key: "C17",
    family: "C17",
    file: "monsters/slimeattikus_anim.png",
    width: 1536,
    height: 186,
    frameWidth: 48,
    frameHeight: 31,
    columns: 32,
    rows: 6,
    anchorX: 26,
    anchorY: 15,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:43, rules :369
  C18: {
    key: "C18",
    family: "C18",
    file: "monsters/slimeattikusmini_anim.png",
    width: 960,
    height: 116,
    frameWidth: 30,
    frameHeight: 20,
    columns: 32,
    rows: 6,
    anchorX: 15,
    anchorY: 11,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:44, rules :192
  C19: {
    key: "C19",
    family: "C19",
    file: "monsters/rezghul.png",
    width: 1536,
    height: 258,
    frameWidth: 48,
    frameHeight: 43,
    columns: 32,
    rows: 6,
    anchorX: 26,
    anchorY: 36,
    directions: 30,
    directionOffset: 0,
    animations: {
      idle: { first: 1, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 5, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:45, rules :211
  IC1: {
    key: "IC1",
    family: "IC1",
    file: "monsters/spurtz.png",
    width: 720,
    height: 84,
    frameWidth: 24,
    frameHeight: 28,
    columns: 30,
    rows: 3,
    anchorX: 12,
    anchorY: 14,
    directions: 32,
    directionOffset: 0,
    animations: {
      walk: { first: 1, count: 2, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:46, rules :369
  IC2: {
    key: "IC2",
    family: "IC2",
    file: "monsters/zagnoid.png",
    width: 1933,
    height: 46,
    frameWidth: 64.4,
    frameHeight: 46,
    columns: 30,
    rows: 1,
    anchorX: 26,
    anchorY: 28,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:47, rules :217
  IC3: {
    key: "IC3",
    family: "IC3",
    file: "monsters/malphus.png",
    width: 1530,
    height: 315,
    frameWidth: 51,
    frameHeight: 35,
    columns: 30,
    rows: 9,
    anchorX: 25,
    anchorY: 17,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 1, count: 8, ticksPerFrame: 8 },
    },
    movement: "jump",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:48, rules :369
  IC4: {
    key: "IC4",
    family: "IC4",
    file: "monsters/valgos.png",
    width: 1650,
    height: 32,
    frameWidth: 55,
    frameHeight: 32,
    columns: 30,
    rows: 1,
    anchorX: 11,
    anchorY: 15,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "burrow",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:49, rules :223
  IC5: {
    key: "IC5",
    family: "IC5",
    file: "monsters/balthazar.png",
    width: 1680,
    height: 259,
    frameWidth: 56,
    frameHeight: 37,
    columns: 30,
    rows: 7,
    anchorX: 33,
    anchorY: 18.5,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 1, count: 6, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "shadow",
    skins: [],
  },
  // SPRITES.as:50, rules :369
  IC6: {
    key: "IC6",
    family: "IC6",
    file: "monsters/grokus.v2.png",
    width: 1718,
    height: 39,
    frameWidth: 57,
    frameHeight: 39,
    columns: 30,
    rows: 1,
    anchorX: 28,
    anchorY: 20,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:51, rules :369
  IC7: {
    key: "IC7",
    family: "IC7",
    file: "monsters/sabnox.png",
    width: 1260,
    height: 34,
    frameWidth: 42,
    frameHeight: 34,
    columns: 30,
    rows: 1,
    anchorX: 21,
    anchorY: 17,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:52, rules :369
  IC8: {
    key: "IC8",
    family: "IC8",
    file: "monsters/wormzer.png",
    width: 1740,
    height: 42,
    frameWidth: 58,
    frameHeight: 42,
    columns: 30,
    rows: 1,
    anchorX: 29,
    anchorY: 21,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "burrow",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:53, rules :229
  G1_1: {
    key: "G1_1",
    family: "G1",
    file: "monsters/ape_1.png",
    width: 1536,
    height: 1035,
    frameWidth: 96,
    frameHeight: 69,
    columns: 16,
    rows: 15,
    anchorX: 48,
    anchorY: 38,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:54, rules :229
  G1_2: {
    key: "G1_2",
    family: "G1",
    file: "monsters/ape_2.png",
    width: 1424,
    height: 1095,
    frameWidth: 89,
    frameHeight: 73,
    columns: 16,
    rows: 15,
    anchorX: 38,
    anchorY: 36,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:55, rules :229
  G1_3: {
    key: "G1_3",
    family: "G1",
    file: "monsters/ape_3.png",
    width: 1648,
    height: 1320,
    frameWidth: 103,
    frameHeight: 88,
    columns: 16,
    rows: 15,
    anchorX: 42,
    anchorY: 52,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:56, rules :229
  G1_4: {
    key: "G1_4",
    family: "G1",
    file: "monsters/ape_4.png",
    width: 2368,
    height: 2032,
    frameWidth: 148,
    frameHeight: 127,
    columns: 16,
    rows: 16,
    anchorX: 52,
    anchorY: 82,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:57, rules :229
  G1_5: {
    key: "G1_5",
    family: "G1",
    file: "monsters/ape_5.png",
    width: 2560,
    height: 2192,
    frameWidth: 160,
    frameHeight: 137,
    columns: 16,
    rows: 16,
    anchorX: 54,
    anchorY: 98,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:58, rules :229
  G1_6: {
    key: "G1_6",
    family: "G1",
    file: "monsters/ape_6.png",
    width: 2240,
    height: 1920,
    frameWidth: 140,
    frameHeight: 120,
    columns: 16,
    rows: 16,
    anchorX: 46,
    anchorY: 80,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:59, rules :229
  G2_1: {
    key: "G2_1",
    family: "G2",
    file: "monsters/dragon_1.png",
    width: 1024,
    height: 615,
    frameWidth: 64,
    frameHeight: 41,
    columns: 16,
    rows: 15,
    anchorX: 32,
    anchorY: 28,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:60, rules :229
  G2_2: {
    key: "G2_2",
    family: "G2",
    file: "monsters/dragon_2.png",
    width: 1392,
    height: 870,
    frameWidth: 87,
    frameHeight: 58,
    columns: 16,
    rows: 15,
    anchorX: 38,
    anchorY: 36,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:61, rules :229
  G2_3: {
    key: "G2_3",
    family: "G2",
    file: "monsters/dragon_3.png",
    width: 1824,
    height: 1275,
    frameWidth: 114,
    frameHeight: 85,
    columns: 16,
    rows: 15,
    anchorX: 52,
    anchorY: 50,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:62, rules :229
  G2_4: {
    key: "G2_4",
    family: "G2",
    file: "monsters/dragon_4.png",
    width: 2096,
    height: 1488,
    frameWidth: 131,
    frameHeight: 93,
    columns: 16,
    rows: 16,
    anchorX: 56,
    anchorY: 52,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:63, rules :229
  G2_5: {
    key: "G2_5",
    family: "G2",
    file: "monsters/dragon_5.png",
    width: 2496,
    height: 1872,
    frameWidth: 156,
    frameHeight: 117,
    columns: 16,
    rows: 16,
    anchorX: 64,
    anchorY: 68,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:64, rules :229
  G2_6: {
    key: "G2_6",
    family: "G2",
    file: "monsters/dragon_6.png",
    width: 2736,
    height: 2000,
    frameWidth: 171,
    frameHeight: 125,
    columns: 16,
    rows: 16,
    anchorX: 70,
    anchorY: 76,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
      attack: { first: 8, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:65, rules :248
  G3_1: {
    key: "G3_1",
    family: "G3",
    file: "monsters/fly_1.png",
    width: 848,
    height: 320,
    frameWidth: 53,
    frameHeight: 40,
    columns: 16,
    rows: 8,
    anchorX: 20,
    anchorY: 21,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 7, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:66, rules :248
  G3_2: {
    key: "G3_2",
    family: "G3",
    file: "monsters/fly_2.png",
    width: 1008,
    height: 414,
    frameWidth: 63,
    frameHeight: 46,
    columns: 16,
    rows: 9,
    anchorX: 38,
    anchorY: 36,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 8, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:67, rules :248
  G3_3: {
    key: "G3_3",
    family: "G3",
    file: "monsters/fly_3.png",
    width: 1568,
    height: 567,
    frameWidth: 98,
    frameHeight: 81,
    columns: 16,
    rows: 7,
    anchorX: 52,
    anchorY: 50,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 6, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "bigshadow",
    skins: [],
  },
  // SPRITES.as:68, rules :248
  G3_4: {
    key: "G3_4",
    family: "G3",
    file: "monsters/fly_4.png",
    width: 1920,
    height: 644,
    frameWidth: 120,
    frameHeight: 92,
    columns: 16,
    rows: 7,
    anchorX: 56,
    anchorY: 52,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 6, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "bigshadow",
    skins: [],
  },
  // SPRITES.as:69, rules :248
  G3_5: {
    key: "G3_5",
    family: "G3",
    file: "monsters/fly_5.png",
    width: 2128,
    height: 735,
    frameWidth: 133,
    frameHeight: 105,
    columns: 16,
    rows: 7,
    anchorX: 60,
    anchorY: 68,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 6, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "bigshadow",
    skins: [],
  },
  // SPRITES.as:70, rules :248
  G3_6: {
    key: "G3_6",
    family: "G3",
    file: "monsters/fly_6.png",
    width: 1984,
    height: 735,
    frameWidth: 124,
    frameHeight: 105,
    columns: 16,
    rows: 7,
    anchorX: 58,
    anchorY: 98,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 1, count: 6, ticksPerFrame: 8 },
    },
    movement: "fly",
    shadow: "bigshadow",
    skins: [],
  },
  // SPRITES.as:71, rules :265
  G4_1: {
    key: "G4_1",
    family: "G4",
    file: "monsters/korath_1.png",
    width: 1152,
    height: 833,
    frameWidth: 72,
    frameHeight: 49,
    columns: 16,
    rows: 17,
    anchorX: 36,
    anchorY: 35,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 8, ticksPerFrame: 8 },
      attack: { first: 8, count: 9, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:72, rules :265
  G4_2: {
    key: "G4_2",
    family: "G4",
    file: "monsters/korath_2.png",
    width: 1904,
    height: 1377,
    frameWidth: 119,
    frameHeight: 81,
    columns: 16,
    rows: 17,
    anchorX: 61,
    anchorY: 49,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 8, ticksPerFrame: 8 },
      attack: { first: 8, count: 9, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:73, rules :265
  G4_3: {
    key: "G4_3",
    family: "G4",
    file: "monsters/korath_3.png",
    width: 2048,
    height: 1836,
    frameWidth: 128,
    frameHeight: 102,
    columns: 16,
    rows: 18,
    anchorX: 52,
    anchorY: 70,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 9, ticksPerFrame: 8 },
      attack: { first: 9, count: 9, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:74, rules :265
  G4_4: {
    key: "G4_4",
    family: "G4",
    file: "monsters/korath_4.png",
    width: 2448,
    height: 2460,
    frameWidth: 153,
    frameHeight: 123,
    columns: 16,
    rows: 20,
    anchorX: 62,
    anchorY: 95,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 10, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:75, rules :265
  G4_5: {
    key: "G4_5",
    family: "G4",
    file: "monsters/korath_5.png",
    width: 3184,
    height: 4860,
    frameWidth: 199,
    frameHeight: 162,
    columns: 16,
    rows: 30,
    anchorX: 81,
    anchorY: 126,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 10, ticksPerFrame: 8 },
      stomp: { first: 20, count: 10, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:76, rules :265
  G4_6: {
    key: "G4_6",
    family: "G4",
    file: "monsters/korath_6.png",
    width: 3232,
    height: 5010,
    frameWidth: 202,
    frameHeight: 167,
    columns: 16,
    rows: 30,
    anchorX: 70,
    anchorY: 130,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 1, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 10, ticksPerFrame: 8 },
      stomp: { first: 20, count: 10, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:77, rules :314
  G5_1: {
    key: "G5_1",
    family: "G5",
    file: "monsters/krallen_1_rev_65.png",
    width: 2080,
    height: 1280,
    frameWidth: 130,
    frameHeight: 80,
    columns: 16,
    rows: 16,
    anchorX: 64,
    anchorY: 50,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 10, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 6, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:78, rules :314
  G5_2: {
    key: "G5_2",
    family: "G5",
    file: "monsters/krallen_2_rev_65.png",
    width: 2096,
    height: 1440,
    frameWidth: 131,
    frameHeight: 90,
    columns: 16,
    rows: 16,
    anchorX: 61,
    anchorY: 60,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 10, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 6, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:79, rules :314
  G5_3: {
    key: "G5_3",
    family: "G5",
    file: "monsters/krallen_3_rev_65.png",
    width: 2272,
    height: 1600,
    frameWidth: 142,
    frameHeight: 100,
    columns: 16,
    rows: 16,
    anchorX: 52,
    anchorY: 72,
    directions: 16,
    directionOffset: 45,
    animations: {
      idle: { first: 0, count: 10, ticksPerFrame: 8 },
      walk: { first: 0, count: 10, ticksPerFrame: 8 },
      attack: { first: 10, count: 6, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:80, rules :346
  C200: {
    key: "C200",
    family: "C200",
    file: "monsters/looter.png",
    width: 1581,
    height: 94,
    frameWidth: 51,
    frameHeight: 47,
    columns: 31,
    rows: 2,
    anchorX: 7,
    anchorY: 33,
    directions: 30,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
      carrying: { first: 1, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:81, rules :338
  shadow: {
    key: "shadow",
    family: "shadow",
    file: "monsters/flyingshadow.png",
    width: 31,
    height: 20,
    frameWidth: 31,
    frameHeight: 20,
    columns: 1,
    rows: 1,
    anchorX: 15,
    anchorY: 10,
    directions: 1,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:82, rules :342
  bigshadow: {
    key: "bigshadow",
    family: "bigshadow",
    file: "monsters/zafreeti-shadow.png",
    width: 48,
    height: 32,
    frameWidth: 48,
    frameHeight: 32,
    columns: 1,
    rows: 1,
    anchorX: 24,
    anchorY: 16,
    directions: 1,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
  // SPRITES.as:83, rules :355
  rocket: {
    key: "rocket",
    family: "rocket",
    file: "monsters/daverocket.png",
    width: 512,
    height: 16,
    frameWidth: 16,
    frameHeight: 16,
    columns: 32,
    rows: 1,
    anchorX: 26,
    anchorY: 36,
    directions: 32,
    directionOffset: 0,
    animations: {
      walk: { first: 0, count: 1, ticksPerFrame: 8 },
    },
    movement: "ground",
    shadow: null,
    skins: [],
  },
};
