#!/usr/bin/env bash
# run-full.sh <batch dir name> <c1> <c2> <c3> <c4> : one batch of 4 Bolt headings (sheet columns, 12 degrees apart,
# 0 = east, clockwise). Needs $R/reference/{frames,portrait,style}.png (see make_batches in the report).
T='D:/Coding/BYMR/art-trials/bolt/kit'
R="$T/$1"; shift
h() { echo "$(( $1 * 12 )) degrees"; }
date +%T
bash ~/.claude/scripts/agy-delegate.sh --write --yolo --timeout 10m --dir "$R" -- "You are repainting tiny game sprites. Workspace folder: $R. reference/portrait.png is the OFFICIAL concept painting of the monster (the Bolt): a red/flesh-coloured fanged worm with cracked skin, a dark black-blue spiked segmented shell on its back with red thorn spikes and small red legs, a ring-shaped mouth full of fangs with a red tongue, and two glowing purple eye bulbs on the sides of its head. reference/style.png is the APPROVED repaint of this monster in 4 directions (2x2 grid: east, south, west, north): copy its exact design, colours, painting style, proportions, shell segments, spike pattern, eye bulbs and mouth for every new cell. reference/frames.png is a 2x2 grid (cells 320x256 px, grey ground) of 4 low-resolution isometric game sprite frames of the same monster blown up 8x (old blurry design), 4 different headings. Heading is measured on the ground from the screen's right (east) turning clockwise as seen from above, so 0 = facing right, 90 = facing toward the viewer (down), 180 = facing left, 270 = facing away (up), and the camera is a 3/4 isometric view. Cell headings: top-left $(h $1), top-right $(h $2), bottom-left $(h $3), bottom-right $(h $4). TASK: generate ONE new image saved as out/frames-new.png with exactly the same 2x2 grid layout and canvas proportions as reference/frames.png (640x512 or a 2x multiple); each monster at the same position, same size, same pose, same facing as the matching cell of frames.png, but redrawn in the style/design of style.png and portrait.png (ignore frames.png's blue/indigo colours). Painted illustration like the portrait, soft shading, glossy highlights, NO outline, not cute, no pixel art. Make it READABLE when shrunk to a tiny size: bright rim light along the top edge of the black shell and clear light highlights on the shell segments and spikes, the red body lit warmly and fairly bright, strong contrast with the ground; keep the same colours as style.png. Fill the cell roughly as much as the old frame does (do not draw smaller than the old monster; same overall bounding box). Each monster casts a soft dark ground shadow. Background everywhere (the whole cell outside the shadow) must be flat pure magenta #FF00FF, no grid lines, no text. IMPORTANT: do NOT write or run any code or scripts, and do NOT warp, cut, copy or composite pixels from any reference image - the new image must be produced by ONE call to your image generation tool, passing all reference images as inputs. Then save it as out/frames-new.png. Reply DONE when the file exists." 2>&1 | tail -4
date +%T; ls -la "$R/out"
